version: '2'
services:
  db:
    image: rethinkdb:latest
    ports:  
      - "38080:8080"
      - "38015:28015"
      - "39015:29015"
  node:
    image: node:latest    
    volumes:
      - ./src/server:/usr/src/server
    working_dir: /usr/src/server
    command: npm start
    ports:
      - "33000:3000"
      - "8080:8080"
    depends_on:
      - db
  ionic:
    image: markwatsonatx/ionic:2.0.0-rc.3
    volumes:
      - ./src/client:/usr/src/client
    working_dir: /usr/src/client
    ports:
      - "38100:8100"
    depends_on:
      - node